name: scheduler
on:
    pull_request:
        types: [opened, synchronize]
    schedule:
        - cron: "0 0,12 * * *"

jobs:
    scheduler:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                combination:
                    - url: https://tix.concertgebouw.nl/nl/buyingflow/tickets/38567/92801/
                      snapshot: ./snapshots/tix.concertgebouw.nl.html
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Run web diff
              run: ./src/web-diff.sh ${{ matrix.combination.url }} ${{ matrix.combination.snapshot }}
